name: Generate Pac-Man Graph

on:
  schedule:
    # Executa automaticamente todos os dias às 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite executar manualmente pela aba Actions do GitHub
  push:
    branches:
      - main
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # 1. Gera as imagens do Pac-Man (Modo Claro e Modo Escuro)
      - name: Generate Pac-Man contribution graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # 2. Envia os arquivos gerados para a branch `pacman-output`
      - name: Push Pac-Man graph to pacman-output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: pacman-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
